### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by Iriscys** [INFO-526-SU24/final-project-dwiesneraz#1]
The following is the peer review of the project proposal by Iris Sum @Iriscys.

- Describe the goal of the project.
To compare the amount of different category trash collected around the Harbor of Baltimore since 2021.

- Describe the data used or collected.
The dataset used is the Trash Wheel Collection Dataset. Much of the data is quantitative, which provide the counts of the various categories of trash. External data including location & businesses data around the areas in which each wheel is located will be added for more insight.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
Plot 1 will present the trash collection data by area in a map.
Plot 2 will present the change of amount of differ trash category since 2021.

- Is there anything that is unclear from the proposal?
The proposal is clear to understand. 

- Provide constructive feedback on how the team might be able to improve their project.
It is a great idea to bring external data to enrich the project! The next step may be to determine whether or not to include further analysis with external businesses data and to what extent will it be analyzed. 

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
Definitely plot 1 in a map, which visualizes the trash collected in different area.

- Provide constructive feedback on any issues with file and/or code organization.
May update the load of package with pacman::p_load.

- (Optional) Any further comments or feedback?

**Comment by dwiesneraz** [comment]
Updated the package install / load section to use pacman format. Clarified use of harbor map in plot 1.
