### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by derekriceX** [INFO-526-SU24/final-project-dwiesneraz#2]
The following is the peer review of the project proposal by [name of team completing peer review]. The team members that participated in this review are 

- Derek Rice - @derekriceX 

- ...

- Describe the goal of the project.

The project goal is to provide actional information about the source of solid pollution to help inform the preferred location to locate a trash collection wheel in the vicinity of the Harbor of Baltimore, Maryland.

- Describe the data used or collected.

The dataset used or collected provides information about four trash collection systems located around the Harbor of Baltimore, Maryland. I assume these are automated wheel based systems setup just upstream of a river mouth to prevent debris from entering the harbor ecosystem. The dataset includes trash category counts based on periodic manual assessment for each category of trash. The trash categories are categorical, the quantity of trash collected is quantitative. 

- Describe how the research question will be answered, e.g. what approaches / methods will be used.

The research question to be answered: Is there a significant difference between the proportions of trash categories between the four collection wheels during the same time period?

The research question will be answered by generating two plots:

Plot 1: compare the proportions of different trash categories between systems for the time they have been in service. 

Plot 2: determine if and how the trash category proportions have changed over time.

- Is there anything that is unclear from the proposal?

The proposal is very clear. Having a table breaking out the tasks helped my understanding of the scope, approach, and effort to be completed. 

- Provide constructive feedback on how the team might be able to improve their project.

I suggested a statistical analysis be included as part of the project. Here, where there are categories (device location, or trash type) with numerical quantities (amount of trash collected, or volume fraction of trash types) an Analysis of Variance could be leveraged to determine if there is a difference in means between categories. 

Analysis of Variance (ANOVA) is used to test for a difference of means between two or more groups. Where a two-sample t-test is limited to comparing the means between two groups, A vs. B for example, an ANOVA can compare mean between two or more groups. 

ANOVA: 
Null Hypothesis Ho: each group/category has the same mean (p-value > 0.05)

Alternative Hypothesis Ha: at least one group has a unique mean (p-value < 0.05)

R has excellent capabilities for completing an ANOVA on this type of dataset. 

You could test the following hypothesis: 

1 -  quantity of trash
Ho: each machine/location collects the same quantity of trash
Ha: at least one machine collects a unique mean quantity of trash

2. volume fraction of trash
Ho: the trash comprises the same amount of each type
Ha: one trash type has a unique mean quantity (i.e. one trash type is more abundent for example) 

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.

I would be interested to know if the location of a trash collection machine has a statistically significant effect on the quantity of trash collected.

Ho: each location collects the same mean quantity of trash
Ha: at least one location collects a unique mean quantity of trash 

- Provide constructive feedback on any issues with file and/or code organization.

I did not have any issues with the file and/or code organization 

- (Optional) Any further comments or feedback?

If you are interested in how to apply an ANOVA to your dataset there is a lot of information available on the internet on how to do the analysis - best of luck - very nice project. I'll be interested to see the final project results.

**Comment by dwiesneraz** [comment]
Included ANOVA testing and hypotheses in proposal.
